/// <reference types="cypress" />

describe("Test suite", function (){
    /*
     * Since no logout is done it will make the follownig test cases to fail
     *
    //Test case 01: Perform login
    it("Perform valid login", function(){
        cy.visit("http://localhost:3000")
        cy.contains('Login') 
        cy.get(':nth-child(1) > input').type('tester01')
        cy.get(':nth-child(2) > input').type('GteteqbQQgSr88SwNExUQv2ydb7xuf8c')
        cy.get('.btn').click()
        cy.contains('Tester Hotel Overview')
   })
*/

    //Test case 02: Perform login
    it("Perform valid login/logout", function(){
            cy.visit("http://localhost:3000")
            cy.contains('Login') 
            cy.get(':nth-child(1) > input').type('tester01')
            cy.get(':nth-child(2) > input').type('GteteqbQQgSr88SwNExUQv2ydb7xuf8c')
            cy.get('.btn').click()
            cy.contains('Tester Hotel Overview')
            cy.get('.user > .btn').click()
            cy.contains('Login')
        })

        //Test case 03: Veiw rooms
    it("View rooms", function(){
            cy.visit("http://localhost:3000")
            cy.contains('Login') 
            cy.get(':nth-child(1) > input').type('tester01')
            cy.get(':nth-child(2) > input').type('GteteqbQQgSr88SwNExUQv2ydb7xuf8c')
            cy.get('.btn').click()
            cy.contains('Tester Hotel Overview')
            cy.get(':nth-child(1) > .btn').click()
            cy.contains('Rooms')
            cy.get(':nth-child(3) > .btn').click()
            cy.contains('Tester Hotel Overview')
            cy.get('.user > .btn').click()
            cy.contains('Login')

        })

    //Test case 04: Create room
    it("Create room", function(){
        cy.visit("http://localhost:3000")
        cy.contains('Login') 
        cy.get(':nth-child(1) > input').type('tester01')
        cy.get(':nth-child(2) > input').type('GteteqbQQgSr88SwNExUQv2ydb7xuf8c')
        cy.get('.btn').click()
        cy.contains('Tester Hotel Overview')
        cy.get(':nth-child(1) > .btn').click()
        cy.contains('Rooms')
        cy.get('h2 > .btn').click()
        cy.contains('New Room')
        cy.get(':nth-child(1) > select').select('Single')
        cy.get(':nth-child(2) > input').type('223')
        cy.get(':nth-child(3) > input').type('2')
        cy.get('.checkbox').click()
        cy.get(':nth-child(5) > input').type('1250')
        cy.get(':nth-child(6) > select').select(['Balcony', 'Sea View'])
        cy.get('.blue').click()
        cy.get(':nth-last-child(1) > :nth-child(2) > h3').contains('Room 223')
        cy.get(':nth-child(3) > .btn').click()
        cy.contains('Tester Hotel Overview')
        cy.get('.user > .btn').click()
        cy.contains('Login')
        
    })

        //Test case 05: Edit single room
        it("Edit single room", function(){
            cy.visit("http://localhost:3000")
            cy.contains('Login') 
            cy.get(':nth-child(1) > input').type('tester01')
            cy.get(':nth-child(2) > input').type('GteteqbQQgSr88SwNExUQv2ydb7xuf8c')
            cy.get('.btn').click()
            cy.contains('Tester Hotel Overview')
            cy.get(':nth-child(1) > .btn').click()
            cy.contains('Rooms')
            cy.get('h2 > .btn').click()
            cy.contains('New Room')
            cy.get(':nth-child(1) > select').select('Single')
            cy.get(':nth-child(2) > input').type('221')
            cy.get(':nth-child(3) > input').type('2')
            cy.get('.checkbox').click()
            cy.get(':nth-child(5) > input').type('1250')
            cy.get(':nth-child(6) > select').select(['Balcony', 'Sea View'])
            cy.get('.blue').click()
            cy.get(':nth-last-child(1) > :nth-child(2) > h3').contains('Room 221')
            cy.get(':nth-last-child(1) > :nth-child(2) > .price').contains('Price: 1250kr')
            cy.get(':nth-last-child(1) > .action > img').click()
            cy.get(':nth-last-child(1) > .menu > :nth-child(1)').click()
            cy.get(':nth-child(7) > input').clear()
            cy.get(':nth-child(7) > input').type('2500')
            cy.get('.blue').click()
            cy.get(':nth-last-child(1) > :nth-child(2) > h3').contains('Room 221')
            cy.get(':nth-last-child(1) > :nth-child(2) > .price').contains('Price: 2500kr')
            cy.get(':nth-child(3) > .btn').click()
            cy.contains('Tester Hotel Overview')
            cy.get('.user > .btn').click()
            cy.contains('Login')
            
        })

    //Test case 06: Delete single room
    it("Edit single room", function(){
        cy.visit("http://localhost:3000")
        cy.contains('Login') 
        cy.get(':nth-child(1) > input').type('tester01')
        cy.get(':nth-child(2) > input').type('GteteqbQQgSr88SwNExUQv2ydb7xuf8c')
        cy.get('.btn').click()
        cy.contains('Tester Hotel Overview')
        cy.get(':nth-child(1) > .btn').click()
        cy.contains('Rooms')
        cy.get('h2 > .btn').click()
        cy.contains('New Room')
        cy.get(':nth-child(1) > select').select('Single')
        cy.get(':nth-child(2) > input').type('222')
        cy.get(':nth-child(3) > input').type('2')
        cy.get('.checkbox').click()
        cy.get(':nth-child(5) > input').type('1250')
        cy.get(':nth-child(6) > select').select(['Balcony', 'Sea View'])
        cy.get('.blue').click()
        cy.get(':nth-last-child(1) > :nth-child(2) > h3').contains('Room 222')
        cy.get(':nth-last-child(1) > :nth-child(2) > .price').contains('Price: 1250kr')
        cy.get(':nth-last-child(1) > .action > img').click()
        cy.get(':nth-last-child(1) > .menu > :nth-child(2)').click()
        cy.get(':nth-last-child(1) > :nth-child(2) > h3').contains('Room 221').should('not.exist')
        cy.get(':nth-last-child(1) > :nth-child(2) > .price').contains('Price: 2500kr').should('not.exist')
        cy.get(':nth-child(3) > .btn').click()
        cy.contains('Tester Hotel Overview')
        cy.get('.user > .btn').click()
        cy.contains('Login')
        
    })


    //Test case 07: Veiw clients
    it("View clients", function(){
            cy.visit("http://localhost:3000")
            cy.contains('Login') 
            cy.get(':nth-child(1) > input').type('tester01')
            cy.get(':nth-child(2) > input').type('GteteqbQQgSr88SwNExUQv2ydb7xuf8c')
            cy.get('.btn').click()
            cy.contains('Tester Hotel Overview')
            cy.get('.blocks > :nth-child(2) > .btn').click()
            cy.contains('Clients')
            cy.get(':nth-child(3) > .btn').click()
            cy.contains('Tester Hotel Overview')
            cy.get('.user > .btn').click()
            cy.contains('Login') 
    })


        //Test case 08: Create client
        it("Create client", function(){
            cy.visit("http://localhost:3000")
            cy.contains('Login') 
            cy.get(':nth-child(1) > input').type('tester01')
            cy.get(':nth-child(2) > input').type('GteteqbQQgSr88SwNExUQv2ydb7xuf8c')
            cy.get('.btn').click()
            cy.contains('Tester Hotel Overview')
            cy.get('.blocks > :nth-child(2) > .btn').click()
            cy.contains('Clients')
            cy.get('h2 > .btn').click()
            cy.contains('New Client')
            cy.get(':nth-child(1) > input').type('Kalle Anka')
            cy.get(':nth-child(2) > input').type('kalle.anka@email.com')
            cy.get(':nth-child(3) > input').type('0701234567')
            cy.get('.blue').click()
            cy.get(':nth-last-child(1) > :nth-child(2) > h3').contains('Kalle Anka')
            cy.get(':nth-child(3) > .btn').click()
            cy.contains('Tester Hotel Overview')
            cy.get('.user > .btn').click()
            cy.contains('Login')
        
       })


            //Test case 09: Edit client
            it("Edit client", function(){
                cy.visit("http://localhost:3000")
                cy.contains('Login') 
                cy.get(':nth-child(1) > input').type('tester01')
                cy.get(':nth-child(2) > input').type('GteteqbQQgSr88SwNExUQv2ydb7xuf8c')
                cy.get('.btn').click()
                cy.contains('Tester Hotel Overview')
                cy.get('.blocks > :nth-child(2) > .btn').click()
                cy.contains('Clients')
                cy.get('h2 > .btn').click()
                cy.contains('New Client')
                cy.get(':nth-child(1) > input').type('Pippi Långstrump')
                cy.get(':nth-child(2) > input').type('pippi@email.com')
                cy.get(':nth-child(3) > input').type('0731234567')
                cy.get('.blue').click()
                cy.get(':nth-last-child(1) > :nth-child(2) > h3').contains('Pippi Långstrump')
                cy.get(':nth-last-child(1) > .action > img').click()
                cy.get(':nth-last-child(1) > .menu > :nth-child(1)').click()
                cy.get(':nth-child(3) > input').clear()
                cy.get(':nth-child(3) > input').type('Pippilotta Långstrump')
                cy.get('.blue').click()
                cy.get(':nth-last-child(1) > :nth-child(2) > h3').contains('Pippilotta Långstrump')
                cy.get(':nth-child(3) > .btn').click()
                cy.contains('Tester Hotel Overview')
                cy.get('.user > .btn').click()
                cy.contains('Login')
            
           })

                  //Test case 10: Delete client
                  it("Delete client", function(){
                    cy.visit("http://localhost:3000")
                    cy.contains('Login') 
                    cy.get(':nth-child(1) > input').type('tester01')
                    cy.get(':nth-child(2) > input').type('GteteqbQQgSr88SwNExUQv2ydb7xuf8c')
                    cy.get('.btn').click()
                    cy.contains('Tester Hotel Overview')
                    cy.get('.blocks > :nth-child(2) > .btn').click()
                    cy.contains('Clients')
                    cy.get('h2 > .btn').click()
                    cy.contains('New Client')
                    cy.get(':nth-child(1) > input').type('Nils Karlsson Pyssling')
                    cy.get(':nth-child(2) > input').type('pyssling@email.com')
                    cy.get(':nth-child(3) > input').type('045521009')
                    cy.get('.blue').click()
                    cy.get(':nth-last-child(1) > :nth-child(2) > h3').contains('Nils Karlsson Pyssling')
                    cy.get(':nth-last-child(1) > .action > img').click()
                    cy.get(':nth-last-child(1) > .menu > :nth-child(2)').click()
                    cy.get(':nth-last-child(1) > :nth-child(2) > h3').contains('Nils Karlsson Pyssling').should('not.exist')
                    cy.get(':nth-child(3) > .btn').click()
                    cy.contains('Tester Hotel Overview')
                    cy.get('.user > .btn').click()
                    cy.contains('Login')
                
               })
})